version: '3.5'

services:
  # abjnet_cli_user:
  #   build: ./user_cli
  #   container_name: "abjnet_cli_user"
  #   environment:
  #    MICRO_REGISTRY: "mdns"
  #   depends_on: 
  #     - "abjnet_user_service"
  abjnet_api_gateway:
    container: abjnet_api_gateway
    restart: always
    build: ./api_gateway
    command: micro api
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    depends_on: 
      - "abjnet_user_service"
      - "abjnet_souscription_service"
      - "abjnet_product_service"
      - "abjnet_email_service"
      - "abjnet_taskrunner_service"
    environment: 
      MICRO_NAMESPACE: "abjnet"
    
  abjnet_user_service:
    container_name: abjnet_user_service
    restart: always
    build: 
      context: ./user_service
      # args:
      #   - HTTP_PROXY=http://127.0.0.1:3138/
      #   - HTTPS_PROXY=http://127.0.0.1:3138/
    ports:
      - 9084:50051
    depends_on: 
      - "database"
    environment: 
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "database:5434"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      #TOKENEXPIRE in minutes
      TOKENEXPIRE: "5"
      MICRO_REGISTERY: "mdns"
  
  abjnet_souscription_service:
    restart: always
    container_name: abjnet_souscription_service
    build: 
      context: ./souscription_service
      # args:
      #   - HTTP_PROXY=http://127.0.0.1:3138/
      #   - HTTPS_PROXY=http://127.0.0.1:3138/
    ports:
      - 9085:50051
    depends_on: 
      - "database"
    environment: 
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "database:5434"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      MICRO_REGISTERY: "mdns"
      TO: "thibaut.zehi@groupensia,"
      CC: "thibaut.zehi@groupensia,"
      #TO: "mariejeanne.pillah@groupensia.com,colombe.brou@groupensia.com"
      #CC: "Exploitation_VIECI@groupensia.com,armel.amacou@groupensia.com,mamery.silue@groupensia.com"

  abjnet_product_service:
    restart: always
    container_name: "abjnet_product_service"
    build: 
      context: ./product_service
      # args:
      #   - HTTP_PROXY=http://127.0.0.1:3138/
      #   - HTTPS_PROXY=http://127.0.0.1:3138/
    ports:
      - 9086:50051
    environment: 
      DB_HOST: "10.8.3.29:57055"
      DB_USER: "reportvie"
      DB_PASSWORD: "reportvie"
      DB_NAME: "SUN_COTEDIVOIRE"
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTERY: "mdns"

  abjnet_email_service:
    restart: always
    container_name: "abjnet_email_service"
    build: 
      context: ./email_service
      # args:
      #   HTTP_PROXY: http://172.17.0.1:3138/
      #   HTTPS_PROXY: http://172.17.0.1:3138/
    ports:
      - 9087:50051
    environment: 
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTERY: "mdns"
      SMTP_HOST: 10.10.4.15
      SMTP_PORT: 25
      FROM: "thibaut.zehi@groupensia.com"

  abjnet_taskrunner_service:
    restart: always
    container_name: "abjnet_taskrunner_service"
    build: 
      context: ./taskrunner_service
      # args:
      #   HTTP_PROXY: http://172.17.0.1:3138/
      #   HTTPS_PROXY: http://172.17.0.1:3138/
    ports:
      - 9088:50051
    environment: 
      DELETESUBSAT: "* * * * *"
      MICRO_SERVER_ADDRESS: ":50051"
      MICRO_REGISTERY: "mdns"

  #we use the default db postgres created   
  database:
      image: postgres
      ports:
        - 5434:5432
      environment: 
        POSTGRES_PASSWORD: "postgres"