version: '3.5'

services:
  nats:
    container_name: nats
    image: nats
    ports: 
      - "4222:4222"
  abjnet_api_gateway:
    container_name: abjnet_api_gateway
    restart: always
    image: micro/micro
    # build: ./api_gateway
    command: api --handler=http --address=:9090 --namespace=abjnet
    network_mode: host
    # ports:
    #   - :8080
    environment:
      MICRO_REGISTERY: "mdns"
      MICRO_NAMESPACE: "abjnet"

  abjnet_api_rest:
    container_name: abjnet_api_rest
    # build: 
    #   context: ./restapi
    image: abjnet_api_rest
    restart: always
    network_mode: host
    
  abjnet_user_service:
    container_name: abjnet_user_service
    restart: always
    image: abjnet_user_service
    # build: 
    #   context: ./user_service
      # args:
      #   - HTTP_PROXY=http://127.0.0.1:3138/
      #   - HTTPS_PROXY=http://127.0.0.1:3138/
    # ports:
    #   - 9084:50051
    depends_on: 
      - "nats"
      - "database"
    network_mode: host
    environment: 
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "127.0.0.1:5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      #TOKENEXPIRE in minutes
      TOKENEXPIRE: "60"
      MICRO_REGISTERY: "mdns"
  
  abjnet_souscription_service:
    restart: always
    container_name: abjnet_souscription_service
    image: abjnet_souscription_service
    # build: 
    #   context: ./souscription_service
      # args:
      #   - HTTP_PROXY=http://127.0.0.1:3138/
      #   - HTTPS_PROXY=http://127.0.0.1:3138/
    # ports:
    #   - 9085:50051
    depends_on: 
      - abjnet_user_service
    network_mode: host
    environment: 
      MICRO_SERVER_ADDRESS: ":50052"
      DB_HOST: "127.0.0.1:5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      MICRO_REGISTERY: "mdns"
      TO: "thibaut.zehi@groupensia,"
      CC: "thibaut.zehi@groupensia,"
      #TO: "mariejeanne.pillah@groupensia.com,colombe.brou@groupensia.com"
      #CC: "Exploitation_VIECI@groupensia.com,armel.amacou@groupensia.com,mamery.silue@groupensia.com"

  abjnet_product_service:
    restart: always
    container_name: "abjnet_product_service"
    image: abjnet_product_service
    # build: 
    #   context: ./product_service
      # args:
      #   - HTTP_PROXY=http://127.0.0.1:3138/
      #   - HTTPS_PROXY=http://127.0.0.1:3138/
    # ports:
    #   - 9086:50051
    depends_on: 
      - abjnet_souscription_service
    network_mode: host
    environment: 
      IN_NSIA: "yes"
      DB_HOST: "10.8.3.29:57055"
      DB_USER: "reportvie"
      DB_PASSWORD: "reportvie"
      DB_NAME: "SUN_COTEDIVOIRE"
      MICRO_SERVER_ADDRESS: ":50053"
      MICRO_REGISTERY: "mdns"

  abjnet_email_service:
    depends_on: 
      - abjnet_product_service
    restart: always
    container_name: "abjnet_email_service"
    image: abjnet_email_service
    # build: 
    #   context: ./email_service
      # args:
      #   HTTP_PROXY: http://172.17.0.1:3138/
      #   HTTPS_PROXY: http://172.17.0.1:3138/
    # ports:
    #   - 9087:50051
    network_mode: host
    environment: 
      MICRO_SERVER_ADDRESS: ":50054"
      MICRO_REGISTERY: "mdns"
      SMTP_HOST: 10.10.4.15
      SMTP_PORT: 25
      FROM: "thibaut.zehi@groupensia.com"
      ADPASSWORD: "ZjjTEnt@1988"

  abjnet_taskrunner_service:
    depends_on: 
      - abjnet_email_service
    restart: always
    container_name: "abjnet_taskrunner_service"
    image: "abjnet_taskrunner_service"
    # build: 
    #   context: ./taskrunner_service
    network_mode: host
      # args:
      #   HTTP_PROXY: http://172.17.0.1:3138/
      #   HTTPS_PROXY: http://172.17.0.1:3138/
    # ports:
    #   - 9088:50051
    environment: 
      DELETESUBSAT: "05 7 * * *"
      DELETEPAYSAT: "05 7 * * *"
      MAJSUBAT: "05 7 * * *"
      MICRO_SERVER_ADDRESS: ":50055"
      MICRO_REGISTERY: "mdns"

  #we use the default db postgres created   
  database:
    image: postgres
    ports:
      - "5434:5432"
    environment: 
      POSTGRES_PASSWORD: "postgres"