version: '3.5'

services:
  # abjnet_cli_user:
  #   build: ./user_cli
  #   container_name: "abjnet_cli_user"
  #   environment:
  #    MICRO_REGISTRY: "mdns"
  #   depends_on: 
  #     - "abjnet_user_service"

  abjnet_user_service:
    restart: always
    build: ./user_service
    ports:
      - 50051:50051
    depends_on: 
      - "database"
    environment: 
      MICRO_SERVER_ADDRESS: ":50051"
      DB_HOST: "database:5433"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      MICRO_REGISTERY: "mdns"

  abjnet_email_service:
    restart: always
    container_name: "abjnet_email_service"
    build: ./email_service
    environment: 
      MICRO_SERVER_ADDRESS: ":50054"
      MICRO_REGISTERY: "mdns"
database:
    image: postgres
    ports:
      - 5433:5432
    environment: 
      POSTGRES_PASSWORD: "postgres"