version: '3.5'

services:
  abjnet_api_gateway:
    container_name: abjnet_api_gateway
    restart: always
    image: micro/micro
    # build: .
    command: api --handler=http --address=:8080 --namespace=abjnet
    ports:
      - 8080:8080
    #   - 8081:8081
    #   - 8082:8082
    network_mode: host
    environment: 
      MICRO_REGISTERY: "mdns"
      MICRO_NAMESPACE: "abjnet"

